version: '3.9'

services:
  catalogdb:
    image: mongo

  cartdb:
    image: redis:alpine

  discountdb:
    image: postgres:alpine

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  rabbitmq:
    image: rabbitmq:management-alpine

  pgadmin:
    image: dpage/pgadmin4

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: src/Services/Cart/Cart.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.gRPC/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}authidentityserver
    build:
      context: .
      dockerfile: src/Services/Identity/Auth.IdentityServer/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile

  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: src/WebApps/WebStatus/WebStatus/Dockerfile

  yarp.proxy:
    image: ${DOCKER_REGISTRY-}yarpproxy
    build:
      context: .
      dockerfile: src/Gateways/YARP.Proxy/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  elasticsearch-data: